### ISSUE TITLE
Request: custom notifications

### ISSUE THREAD

**Issue by megusta-01** [porech/roborock-oucher#10]
I've an idea to give some sound notifications over roborock. Can you realise that?
For example you can use mqtt to send messages from other devices to roborock to say "Battery is under 50%" or "Clean the container" or other custom messages. Or if it possible to repeat messages from Alexa for example

**Comment by ale-rinaldi** [comment]
Hello,

yeah, could be a great idea! I will try to work on it, but it will probably be a different project.

Thanks!
