### ISSUE TITLE
No bumper logs

### ISSUE THREAD

**Issue by jontemalm** [porech/roborock-oucher#11]
Hi,
I have a Roborock S5 and can't get the oucher to say anything. After some debugging I have found that I have no logs which contains the bumper-info. 
I can find the following logs when the vacuum is running but only the first one contains any data and I can't find any log named "PLAYER_fprintf.log".
Does someone know in which file the Roborock S5 should log the bumper info?

-rw-r--r--    1 root     root        161201 Jan  9 12:38 NAV_TRAP_fprintf.log
-rw-r--r--    1 root     root             0 Jan  9 03:30 NAV_TRAP_normal.log
-rw-r--r--    1 root     root             0 Jan  9 03:30 NAV_normal.log
-rw-r--r--    1 root     root             0 Jan  9 12:37 NAV_normal_pl9.log

**Comment by ale-rinaldi** [comment]
Hello,

thanks for your report. As a first attempt I would check how the log level is set in /opt/rockrobo/rrlog/rrlogd.conf : try setting it to 8, that is the most verbose one.

Also, if you can please send me the content of the log files at oucher@alerinaldi.it : maybe the name of the files to be monitored should be changed.

**Comment by ale-rinaldi** [comment]
Hello @jontemalm ,

sorry if I totally ignored your last mail but I've little to no time for Oucher at the moment :( Also, thanks for the solution you provided me.

For everyone else having the same issue, you should change LOG_LEVEL to 8 in `/opt/rockrobo/rrlog/rrlog.conf` and make sure you're using the latest binary I uploaded today to the repository.

Thanks againi
