### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by gatesry** [porech/roborock-oucher#14]
**Model:** Roborock S5 Max
**Valetudo Ver:** 2021.3.17
**Dustbin:** DustBuilder FW compiled yesterday
**Issue:** When installing Oucher files, getting read-only file system errors that are preventing mkdir commands from executing. Through looking around, is this caused by squash file system? What other steps are needed to remount the fs?

`mkdir: can't create directory '/usr/local': Read-only file system`

**Comment by ale-rinaldi** [comment]
Hello @mazak-ui ,

the strangest think I see is that you have to create the /usr/local folder, it should already exist. Are you sure it isn't there?

Thanks

**Comment by mazak-ui** [comment]
Hey @ale-rinaldi ,

Glad I'm not the only one that thinks this is weird. I'm also asking in the Valetudo telegram channel to see about this read-only fs error.

Yes, confirmed it's not there. See enclosed.

![image](https://user-images.githubusercontent.com/67442967/113315974-7db99080-92d3-11eb-8e4d-c5e019f518b6.png)

Thank you

**Comment by ale-rinaldi** [comment]
Great, let me know. I'm also asking about this on the [dustcloud group](https://t.me/joinchat/Fl7Mm0iEV7Pgf9ngDyly-g) if you wanna join

**Comment by mazak-ui** [comment]
Thanks, just joined. Send me a ping if you could.

**Comment by mazak-ui** [comment]
Just an update for anyone else seeing this. Currently, with the S5M, the system is `squashfs` and primarily in a read-only state.

**Comment by henriklied** [comment]
For anyone else having trouble with this, I figured out that my S5 Max writes the bump to the logfile /run/shm/NAV_TRAP_normal.log as TrapHardWalkDetector messages.

The following file is an example of how I'm using node js to send an UDP message each time there's a bump event:
[s5-max-oucher.js.txt](https://github.com/porech/roborock-oucher/files/7640280/s5-max-oucher.js.txt)

**Comment by ale-rinaldi** [comment]
Hello @henriklied ,
thank you very much for your feedback! I'd like to add this recognition pattern to Oucher. Can you please send me a log captured after the robot started and made some bumps, so I can be as specific as possible in the match and avoid false positives.
Thank you!

**Comment by henriklied** [comment]
Sure, @ale-rinaldi!
All the lines containing **TrapHardWalkDetector** below from `/run/shm/NAV_TRAP_normal.log` are when it bumps. You also get number of bumps since the start of the cleaning session.

```
155, 24201263 T20725 TrapHardWalkDetector:1263 [info]  HandleTrap TrapHardWalkDetector  bumper counter = 1 source[[Left:Bumper]]
156, 24201462 T20724 CalHardWalk:1399 [info]  HandleTrap CalHardWalk push_back [93 -5 -0.06][265,28] time:3 size:1
157, 24206424 T20725 TrapHardWalkDetector:1263 [info]  HandleTrap TrapHardWalkDetector  bumper counter = 2 source[[Right:Bumper]]
158, 24206465 T20724 CalHardWalk:1399 [info]  HandleTrap CalHardWalk push_back [163 402 -0.70][203,233] time:4 size:2
159, 24207662 T20725 TrapHardWalkDetector:1263 [info]  HandleTrap TrapHardWalkDetector  bumper counter = 3 source[[Right:Bumper]]
160, 24207664 T20724 CalHardWalk:1399 [info]  HandleTrap CalHardWalk push_back [215 407 0.08][260,239] time:4 size:3
161, 24209683 T20725 TrapHardWalkDetector:1263 [info]  HandleTrap TrapHardWalkDetector  bumper counter = 4 source[[Right:Bumper]]
162, 24209861 T20724 CalHardWalk:1399 [info]  HandleTrap CalHardWalk push_back [373 448 0.04][417,280] time:3 size:4
163, 24212004 T20725 TrapHardWalkDetector:1263 [info]  HandleTrap TrapHardWalkDetector  bumper counter = 5 source[[Right:Bumper]]
164, 24212061 T20724 CalHardWalk:1399 [info]  HandleTrap CalHardWalk push_back [521 483 -0.44][659,375] time:2 size:5
165, 24212863 T20725 TrapHardWalkDetector:1263 [info]  HandleTrap TrapHardWalkDetector  bumper counter = 6 source[[Right:Bumper]]
166, 24212868 T20724 CalHardWalk:1399 [info]  HandleTrap CalHardWalk push_back [530 490 -0.02][661,375] time:6 size:6
```

**Comment by ale-rinaldi** [comment]
Hello @henriklied ,

can you please try the build at https://github.com/porech/roborock-oucher/raw/fix/17-14-s5-max-compatibility-and-ouches-on-start/oucher ? This should work.

Thank you!

**Comment by mazak-ui** [comment]
I'm getting my board back from DGI soon and I will test this build as well.

**Comment by Groger63** [comment]
Hey, with :
Model: Roborock S5 Max
Valetudo Ver: 2022.11.0
Dustbin: DustBuilder FW compiled 23/12/2022

I can't install oucher with initd, but I can launch and run it from ssh, with small modification to config file.

![Capture d’écran du 2022-12-28 16-23-23](https://user-images.githubusercontent.com/15104404/209834132-95409808-d0c4-4f57-bd34-30c2b10838e5.png)

I will try to edit /mnt/reserve/_root.sh to launch it from there during next week, and tell how it goes afterwards

![Capture d’écran du 2022-12-29 09-16-25](https://user-images.githubusercontent.com/15104404/209923411-cfb61c12-ffb9-4777-877f-e18a0a8c2a8f.png)
