### ISSUE TITLE
Robot ouches on start of cleaning

### ISSUE THREAD

**Issue by jaredthejellyfish** [porech/roborock-oucher#17]
The robot ouches whenever I trigger the start of any cleaning program.

**Comment by ale-rinaldi** [comment]
Hi @jarredthejellyfish , thanks for the report. Maybe some models log a bumper reset that I mistreat as a bump.

Can you please collect the logs for me? There are indications on what logs I need in the README.

Thank you!

**Comment by jarredthejellyfish** [comment]
Yes, sorry, I completely forgot to upload them.
[NAV_TRAP_normal.log](https://github.com/porech/roborock-oucher/files/7076633/NAV_TRAP_normal.log)
[PLAYER_fprintf.log](https://github.com/porech/roborock-oucher/files/7076634/PLAYER_fprintf.log)
[NAV_normal.log](https://github.com/porech/roborock-oucher/files/7076635/NAV_normal.log)

**Comment by ale-rinaldi** [comment]
Hello @jarredthejellyfish , sorry for the delay :(

Can you please try with the executable at https://github.com/porech/roborock-oucher/raw/fix/17-14-s5-max-compatibility-and-ouches-on-start/oucher and confirm me the problem is solved?

Thank you!

**Comment by 857GIT** [comment]
Hello

I can confirm that fix didnt work on this issue.

My roborock S6 also ouched on start and also when docking.

Here is my logs: (I didnt have that PLAYER_fprintf.log file)

[NAV_normal.log](https://github.com/porech/roborock-oucher/files/7698855/NAV_normal.log)
[NAV_TRAP_normal.log](https://github.com/porech/roborock-oucher/files/7698856/NAV_TRAP_normal.log)

**Comment by ale-rinaldi** [comment]
Thank you @jarredthejellyfish , it's funny how everytime I see a log I find something new in it :)

Can you please again? The link is the same, I just updated the build in the branch: https://github.com/porech/roborock-oucher/raw/fix/17-14-s5-max-compatibility-and-ouches-on-start/oucher 

Thank you

**Comment by 857GIT** [comment]
Nope sorry, still ouching at start.

Do you want the new logs?

Btw I'm not OP =)

**Comment by ale-rinaldi** [comment]
Hello @857GIT ,
yeah, I'd like to see the logs after you start it and make some bumps.
Thank you!

**Comment by ale-rinaldi** [comment]
Hello @jaredthejellyfish and @857GIT ,

I know long time passed and I'm sorry I couldn't manage to solve the issue.

If you're still having the problem, I kindly ask you to:
- Copy the `oucher.yml` file inside this repo into `/mnt/data/oucher`
- Add this line at the end of it:
```
logLevel: trace
```
- Kill oucher if already started via autostart: `killall oucher`
- Run it manually redirecting the stderr to a file: `./oucher 2> /tmp/oucher.log`
- Run a clean
- Take the `/tmp/oucher.log` file and send it to me

Thank you for your support

**Comment by ale-rinaldi** [comment]
Meanwhile, I think I found the problem; please try the latest build in the master branch before taking the logs.
Thank you!
