### ISSUE TITLE
Where is oucher_deps.tgz?

### ISSUE THREAD

**Issue by MetalOctopus** [porech/roborock-oucher#18]
"The awesome guys at the dustcloud project put together all the needed binary dependencies in a single tgz file, which you can find in this repo as oucher_deps.tgz. You should be fine by just copying it to the robot and uncompress it in the root folder"

I'm embarrassingly lost and can't seem to find this .tgz...
Could you point me in the right direction, please?

Thank you!

**Comment by ale-rinaldi** [comment]
Hello @MetalOctopus ,
sorry I didn't remove that specific part from the README. The latest versions of `oucher` have no dependencies at all, so you shouldn't need that file! :)

**Comment by MetalOctopus** [comment]
Oh I see  - thanks for the info :)
I followed the readme to the letter, with no ouchies. 
I was hoping it was a simple fix, but looks like I'm troubleshooting :D

**Comment by ale-rinaldi** [comment]
That's sad :( should you need any help, let's keep in touch!
