### ISSUE TITLE
[Discussion] What sounds are you guys using?

### ISSUE THREAD

**Issue by erkexzcx** [porech/roborock-oucher#28]
Since discussions are disabled of this repo, I am raising it as an issue. Sorry @porech if you believe this "issue" is inappropriate. :v:

Anyway, what sounds are you guys using? Personally I've had amazing experience with Half Life 1 scientists scream sounds. They are very short (up to 1-1.5 seconds) and at 30%-50% of volume sound really great!
```
[root@rockrobo sounds]# ls -lh
-rw-r--r--    1 root     root        5.3K Sep 22 12:41 scream10.wav
-rw-r--r--    1 root     root        6.8K Sep 22 12:41 scream11.wav
-rw-r--r--    1 root     root        5.6K Sep 22 12:41 scream12.wav
-rw-r--r--    1 root     root        6.1K Sep 22 12:41 scream13.wav
-rw-r--r--    1 root     root        4.7K Sep 22 12:41 scream14.wav
-rw-r--r--    1 root     root        3.0K Sep 22 12:41 scream15.wav
-rw-r--r--    1 root     root        2.3K Sep 22 12:41 scream16.wav
-rw-r--r--    1 root     root        3.7K Sep 22 12:41 scream17.wav
-rw-r--r--    1 root     root        3.0K Sep 22 12:41 scream18.wav
-rw-r--r--    1 root     root        2.4K Sep 22 12:41 scream19.wav
```
Can't post them here, since they are copyrighted.

**Comment by ale-rinaldi** [comment]
Hi there,

I'm answering a little late, sorry :D

Thanks for make me notice that discussions were not enabled, I just enabled them! Please feel free to propose this topic again on the discussions.

About the sounds, my favorite ones so far are the screams of Pingu: you can find them, and other ones, here: https://www.linuxzogno.org/oucher-sounds/
