### ISSUE TITLE
Log file location and bumper event log for Roborock S5 

### ISSUE THREAD

**Issue by pqvark** [porech/roborock-oucher#29]
Hi! Thank you for your work :)

I own a rooted Roborock S5 with Valetudo version 2023.12.0. I built my dustbuilder image using the Firmware version 2034, 11/2020.

Oucher is not working in my setup. I found out that my version doesn't use the "player" software anymore, but instead it uses something called "rr_loader". That's why I don't have the /run/shm/PLAYER_fprintf.log file in my system. 

The other NAV_* log files included in the source code don't log any "bumper" event, so they didn't work for me. 

After some (hard) insight, I found out that the right log file to look for bumper events in my setup is /run/shm/RRLDR_SERVER_normal.log 

When the bumper hits, a lot of event data is logged in. And a valid line in this log should include the text "Bumper On" (without quotes). 

Hope this helps someone with a similar setup.

Cheers!

**Comment by ale-rinaldi** [comment]
Hi @pqvark and thank you for your feedback! I like Oucher working with the default configurations, so I'd like to implement this as a default path to watch for logs and string to match on.

Would you mind sharing a log file after some bumps so I can double check for possible false positives?

Thank you!

**Comment by ale-rinaldi** [comment]
Hello @pqvark ,

no problem at all, I'm happy you finally got it working!

Maybe you changed the LOG_LEVEL in rrlog.conf? As far as I know it logs only when it's set to something like 8.

Thanks for the feedback on the build, I'm going to dismiss that branch then. If you're having other issues we'll go back on that path, but I'll need the full log file to investigate the false positives.
