### ISSUE TITLE
Cannot find oucher.yml in the /mnt/data/oucher directory

### ISSUE THREAD

**Issue by Sineater224** [porech/roborock-oucher#34]
Im just trying to add a delay to the screaming. I cannot find the yml file. If I go to the oucher directory, I can find a file called oucher which does not work with nano.

**Comment by ale-rinaldi** [comment]
Hi there,

it's OK, Oucher does not need a config file to work, it will just work with the default values if it's not present.

If you need to customize the parameters you can just create the config file yourself, or copy the oucher.yml file that you find in this repository and then customize it. You can find all the information in the readme: https://github.com/porech/roborock-oucher/?tab=readme-ov-file#how-can-i-customize-the-parameters

Please let me know if this helped to solve! Happy ouching :)
