### ISSUE TITLE
Works on Roborock Q7 Max+

### ISSUE THREAD

**Issue by DiegoBotija** [porech/roborock-oucher#35]
In case you want to add it to the readme

**Comment by ale-rinaldi** [comment]
Cool, thank you @DiegoBotija ! Did it work out of the box, or you had to do some magic?

**Comment by DiegoBotija** [comment]
It worked just running the `oucher` and putting some files in the `sounds` folder. I didn't try to run the process at startup as I don't want it running always.
No need to change the LOG_LEVEL, mine was at 6 (the log config file is in a read only mount).
New robots of this model are not rooteable anymore (for now at least), so obviously it only applies to rooted ones.
