### ISSUE TITLE
Works on Roborock S7 Pro Ultra

### ISSUE THREAD

**Issue by hartrusion** [porech/roborock-oucher#36]
Just want to report back that it works on **Roborock S7 Pro Ultra**, Firmware 0184 with Valetudo Release 2024.11.0

No need to edit the rrlog.conf (its not writeable anyway). /etc/init is not writable but Solution #3 works fine. 

Compared to the built in system voice, the ouches are really loud so using the oucher.yml with volume set to some value between 25 to 40 is fine.

Thanks for the awesome work. Really adds some weird personality to the device ;-)

**Comment by ale-rinaldi** [comment]
Thanks for the feedback! Yeah, "weird" personality is the best term to use :P
I'm adding it to the list of supported devices. Happy ouching!
