### ISSUE TITLE
Binary files

### ISSUE THREAD

**Issue by dimmuboy** [porech/roborock-oucher#5]
Can you provide binary files?
I'm using **vacuum_valetudo_re_2008.pkg** firmware by [zvldz](https://github.com/zvldz/vacuum) and I don't have aptitude and dpkg too.

**Comment by jds11111** [comment]
Not sure that it works on newer models. The log files don't show any 'bumper' in the strings.

**Comment by ale-rinaldi** [comment]
Hi there,
sorry for my huuuuge delay.

The guys at dustcloud did an awesome job and prepared a tar package with all the needed dependencies: https://builder.dontvacuum.me/stuff/oucher-deps.tar.gz

Unpack it with tar -xzvf into /

Let me know how it works :)

**Comment by vansoest** [comment]
@ale-rinaldi the URL is dead. 

Will it now work with the latest roborock firmware? Because they removed the sensor information from the logs so the oucher can not parse the sensor information to play the ouch sample.

**Comment by ale-rinaldi** [comment]
Hello @vansoest ,

please look at the issue https://github.com/porech/roborock-oucher/issues/11 I just updated.

Basically yes, as long as you use the latest binary (I just changed it in the repo) and you set LOG_LEVEL to 8 in `/opt/rockrobo/rrlog/rrlog.conf`.
